### PR TITLE
allow building on Scala 2.13 and JDK 12+

### PR DESCRIPTION
**Pull request by SethTisue**
this came up in the Scala community build

### CODE REVIEW

**Comment by SethTisue** [comment]
hmm... I'm no longer convinced this has anything to do with https://github.com/scala/community-build/pull/996 / https://github.com/playframework/playframework/issues/9586

**Comment by marcospereira** [comment]
Hey @SethTisue, I think this would fix the problem. Right now, I don't even see why to use `1.6` source/target for Scala 2.10. Is that related to Scala 2.10 not supporting Java 8?

**Comment by marcospereira** [comment]
Hum, answering my own question:

https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#version-compatibility-table

So, it looks like we can just target `1.8` from now on. 🤔

**Comment by mkurz** [comment]
See https://github.com/playframework/playframework/issues/9586#issuecomment-775146894

**Pull request closed without merging**
