### PR TITLE
Extract each plugin to its own source file

### PR DESCRIPTION
**Pull request by ignasi35**
This refactor extracts every plugin from `PlayBuildase.scala` into a separate source file.

Makes code more navigable and cleans up imports.

### CODE REVIEW

**Comment by ignasi35** [comment]
I was cosidering bumping the version to `2.2.0` after this.

**Comment by renatocaval** [comment]
@ignasi35, there is a merge conflig now. Could you fix it?

**Comment by ignasi35** [comment]
I'll keep rebasing this but I don't think we should merge it until Play and Lagom GA's are out.

**Comment by renatocaval** [comment]
@dwijnand, why did you block-merge this one?

**Comment by dwijnand** [comment]
> I don't think we should merge it until Play and Lagom GA's are out.

**Pull request merged**
