### PR TITLE
Update to Scala 2.12.3

### PR DESCRIPTION
**Pull request by richdougherty**
I tested this version of Scala on _playframework_'s _master_ branch and it compiled and all tests passed.

### CODE REVIEW

**Comment by marcospereira** [comment]
By the way, we should probably revert #26 until we have https://github.com/playframework/play-ws/pull/170 and other possible dependencies resolved.

This way, support Scala 2.13 won't block upgrading to 2.12.3.

**Comment by marcospereira** [comment]
Or giving it a second thought, we should cut a new branch (1.3.x) without 2.13 support and backport 2.12.3 upgrade there. This way we can start to better interplay versioning and avoid such incompatibilities.

WDYT?

**Comment by gmethvin** [comment]
I think we'll need to add Scala 2.13 manually to each project as the dependencies become available on 2.13. It probably doesn't make sense to have interplay force 2.13 for all projects.

**Comment by richdougherty** [comment]
Could we give Interplay a switch to enable/disable Scala 2.13 support until it's working on all our projects?

**Comment by marcospereira** [comment]
Between the switch and manually adding the Scala 2.13, I think we better manually add the project since a switch will require changes in both interplay and projects.

@richdougherty, what do you think?

**Comment by richdougherty** [comment]
Sure that makes sense if it's less work to just add it manually. I was just thinking that using Interplay with a feature switch would guarantee that we add 2.13 in a standardised way across our projects.

**Pull request merged**
